DROP DATABASE IF EXISTS MINIPJ1;
CREATE DATABASE MINIPJ1;
USE MINIPJ1;

CREATE TABLE USERLIST(
    USERNO INT NOT NULL AUTO_INCREMENT,
    CONSTRAINT PRIMARY KEY(USERNO),
    USERID VARCHAR(30) NOT NULL  UNIQUE,
    USERPW VARCHAR(50) NOT NULL,
    USERNAME VARCHAR(20) NOT NULL,
    ROLENO INT,
    CONSTRAINT FOREIGN KEY(ROLENO) REFERENCES ROLE(ROLENO)
);
CREATE TABLE STUDYTYPE(
    STUDYTYPENO INT NOT NULL AUTO_INCREMENT,
    CONSTRAINT PRIMARY KEY(STUDYTYPENO),
    STUDYTYPENAME VARCHAR(50) NOT NULL
);
CREATE TABLE CATEGORY(
    CATEGORYNO INT NOT NULL AUTO_INCREMENT,
    CONSTRAINT PRIMARY KEY(CATEGORYNO),
    CATEGORYNAME VARCHAR(20) NOT NULL 
);
CREATE TABLE ROLE(
    ROLENO INT NOT NULL AUTO_INCREMENT,
    CONSTRAINT PRIMARY KEY(ROLENO),
    ROLENAME VARCHAR(20) NOT NULL 
);
CREATE TABLE STUDYLIST(
    CONTENTNO INT NOT NULL AUTO_INCREMENT,
    CONSTRAINT PRIMARY KEY(CONTENTNO),
    TITLE VARCHAR(100) NOT NULL,
    USERNO INT,
    CONSTRAINT FOREIGN KEY(USERNO) REFERENCES USERLIST(USERNO),
    CATEGORYNO INT,
    CONSTRAINT FOREIGN KEY(CATEGORYNO) REFERENCES CATEGORY(CATEGORYNO),
    STUDYTYPENO INT,
    CONSTRAINT FOREIGN KEY(STUDYTYPENO) REFERENCES STUDYTYPE(STUDYTYPENO),
    MAXMEMBER INT NOT NULL,
    DETAIL LONGTEXT NOT NULL,
    CONTENTDATE DATETIME DEFAULT NOW()
);